# All values in no. of frames.
Training: [{'soa': 50, 'reps':1}, {'soa': 20, 'reps':1}, {'soa': 15, 'reps':1},{'soa': 10, 'reps':1}]
# List describing training.
# In example above it will be four levels of training (because of 4 items in list, may be less, may be more)
# First training block contains 6 trials, (reps = 6) of soa equal to 30 etc...
START_SOA: 18
FIXTIME: 220 # Fixation cross time
MTIME: 50 # Mask presentation time
RTIME: 500 # Maximal response time
MAX_REVS: 1 # No of reversals in adaptive alg.
MAX_REVS: 1 # No of reversals in adaptive alg.
STEP_UP: 1
STEP_DOWN: 1