# All values in no. of frames.
Training_level_1: 30
Training_level_2: 20
Training_level_3: 10
Training_level_4: 5
FIXTIME: 30 # Fixation cross time
MTIME: 20 # Mask presentation time
RTIME: 240 # Maximal response time
STEP_UP: 1
STEP_DOWN: 1