# All values in no. of frames.
TRAINING_TRIALS: [ 3, 3 ]
TRAINING_SOAS: [ 12, 6 ]
# both above list must be equal in length
START_SOA: 6
FIX_TIME: 45
MTIME: 17 # Mask presentation time
RTIME: 240 # Maximal response time
RESTTIME: 240
REST_TIME_RANGE: [ 45, 60 ]
MAX_REVS: 2 # No of reversals in adaptive alg.
STEP_UP: 2
STEP_DOWN: 1
