# All values in no. of frames.
NO_TRIALS: 40
START_SOA: 6
FIXTIME: 75 # Fixation cross time
MTIME: 17 # Mask presentation time
RTIME: 240 # Maximal response time
MAX_REVS: 10 # No of reversals in adaptive alg.
STEP_UP: 3
STEP_DOWN: 1
