# All values in no. of frames.
NO_TRIALS: 90
START_SOA: 6
TRAIN_FIX_TIME: 20
EXP_FIX_TIME: 480
MTIME: 17 # Mask presentation time
RESTTIME: 240
RTIME: 240  # Maximal response time
MAX_REVS: 8 # No of reversals in adaptive alg.
STEP_UP: 3
STEP_DOWN: 1
