# All values in no. of frames.
NO_TRIALS: 1
START_SOA: 8
FIXTIME: 75 # Fixation cross time
MTIME: 17 # Mask presentation time
RTIME: 240 # Maximal response time
MAX_REVS: 2 # No of reversals in adaptive alg.
STEP_UP: 1
STEP_DOWN: 1
